#ifndef OS_PLAYER_COMMONS_H
#define OS_PLAYER_COMMONS_H

#include <stdbool.h>
#include "engine/input.h"

typedef enum {
  PLAYER_STATE_IDLE,
  PLAYER_STATE_READY_TYPE,
  PLAYER_STATE_TRANSACT,
  PLAYER_STATE_DROP,
  PLAYER_STATE_TOWN_ATTACK
} PLAYER_STATE;

typedef enum {
  READY_STEP_START = 0,
  READY_STEP_SELECT_TYPE = 1,
  READY_STEP_WEAPON_INPUT = 2,
  READY_STEP_WEAPON_EQUIP = 3,
  READY_STEP_ARMOR_EQUIP = 4,
  READY_STEP_SPELL_EQUIP = 5,
  READY_STEP_SPELL_LADDER = 6,
  READY_STEP_SPELL_PRAYER_OR_PROJECTILE = 7,
  READY_STEP_RETURN_TO_IDLE = 8
} READY_STEP;

typedef enum {
  TRANSACT_STEP_START = 0,
  TRANSACT_STEP_SELECT_TRANSACTION = 1,
  TRANSACT_STEP_BUY_ITEM = 2,
  TRANSACT_STEP_SELL_ITEM = 3,
  TRANSACT_STEP_SELECT_ITEM = 4,
  TRANSACT_STEP_DRINK_AT_PUB = 5,
  TRANSACT_STEP_SELECT_SELL_ITEM = 6,
  TRANSACT_STEP_CONFIRM_SELL_ITEM = 7
} TRANSACT_STEP;

typedef enum {
  MERCHANT_TYPE_TRANSPORT = 0,
  MERCHANT_TYPE_MAGIC = 1,
  MERCHANT_TYPE_PUB = 2,
  MERCHANT_TYPE_ARMORY = 3,
  MERCHANT_TYPE_WEAPONS = 4,
  MERCHANT_TYPE_FOOD = 5
} MERCHANT_TYPE;

typedef enum {
  DROP_STEP_START = 0,
  DROP_STEP_SELECT_GOLD = 1,
  DROP_STEP_SELECT_WEAPON = 2,
  DROP_STEP_SELECT_ARMOR = 3
} DROP_STEP;

extern PLAYER_STATE playerState;

bool playerCommons_updateZtats();
bool playerCommons_updateWait();
bool playerCommons_updateReady();

#endif