#ifndef OS_CONFIG_H
#define OS_CONFIG_H

#define OS_SCREEN_WIDTH 280
#define OS_SCREEN_HEIGHT 192
#define OS_FONT_WIDTH 128
#define OS_FONT_HEIGHT 128
#define OS_FONT_OFFSET 32
#define OS_FONT_GLYPH_WIDTH 7
#define OS_FONT_GLYPH_HEIGHT 8
#define OS_QUAD_VERTEX_SIZE 20
#define OS_QUAD_INDEX_SIZE 6
#define OS_BTERRA_MAP_WIDTH 64
#define OS_BTERRA_MAP_HEIGHT 64
#define OS_BTERRA_COUNT 4
#define OS_TILE_WIDTH 14
#define OS_TILE_HEIGHT 16

#define OS_ARMORS_COUNT 5
#define OS_VEHICLES_COUNT 6
#define OS_WEAPONS_COUNT 15
#define OS_SPELLS_COUNT 11
#define OS_GEMS_COUNT 4

#endif