#ifndef OS_CONFIG_H
#define OS_CONFIG_H

#define OS_SCREEN_WIDTH 280
#define OS_SCREEN_HEIGHT 192
#define OS_FONT_WIDTH 128
#define OS_FONT_HEIGHT 128
#define OS_FONT_OFFSET 32
#define OS_FONT_GLYPH_WIDTH 7
#define OS_FONT_GLYPH_HEIGHT 8
#define OS_QUAD_VERTEX_SIZE 20
#define OS_QUAD_INDEX_SIZE 6

#endif